### ISSUE TITLE
Cannot open resource with notebook editor type 'isql'

### ISSUE THREAD

**Issue by neongreen** [ducklake-hq/ducklab#12]
I created an `.isql` file and got:

> The editor could not be opened due to an unexpected error: Cannot open resource with notebook editor type 'isql', please check if you have the right extension installed and enabled.

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/a59eb551-8382-4649-adbf-409de0bf28b4">

In the extension settings, I see:

> Menu item references a command ducklab.listKernels which is not defined in the 'commands' section.

<img width="789" alt="image" src="https://github.com/user-attachments/assets/c5636b74-2e37-4426-9643-907509409d45">

**Comment by ehassaan** [comment]
Hi @neongreen thanks for reporting the issue. It is fixed. Please update your extension.
